// 图标选项列表 (Font Awesome 6 版本)
export const iconOptions = [
    // 建议添加一些常用的圆形图标：
    { label: "圆形检查", value: "fas fa-circle-check" },
    { label: "圆形叉", value: "fas fa-circle-xmark" },
    { label: "圆形问号", value: "fas fa-circle-question" },
    { label: "圆形信息", value: "fas fa-circle-info" },
    { label: "圆形警告", value: "fas fa-circle-exclamation" },
    { label: "圆形加", value: "fas fa-circle-plus" },
    { label: "圆形减", value: "fas fa-circle-minus" },
    { label: "圆形用户", value: "fas fa-circle-user" },

    // 基础图标
    { label: "书籍", value: "fas fa-book" },
    { label: "文件", value: "fas fa-file" },
    { label: "文件文本", value: "fas fa-file-lines" },
    { label: "文件PDF", value: "fas fa-file-pdf" },
    { label: "文件图片", value: "fas fa-file-image" },
    { label: "文件代码", value: "fas fa-file-code" },
    { label: "文件音频", value: "fas fa-file-audio" },
    { label: "文件视频", value: "fas fa-file-video" },
    { label: "文件压缩", value: "fas fa-file-zipper" },
    { label: "文件Word", value: "fas fa-file-word" },
    { label: "文件Excel", value: "fas fa-file-excel" },
    { label: "文件PowerPoint", value: "fas fa-file-powerpoint" },
    { label: "文件CSV", value: "fas fa-file-csv" },
    { label: "文件导入", value: "fas fa-file-import" },
    { label: "文件导出", value: "fas fa-file-export" },
    { label: "剪贴板列表", value: "fas fa-clipboard-list" },

    // 文件夹图标
    { label: "文件夹", value: "fas fa-folder" },
    { label: "打开文件夹", value: "fas fa-folder-open" },
    { label: "文件夹加", value: "fas fa-folder-plus" },
    { label: "文件夹减", value: "fas fa-folder-minus" },

    // 对象图标
    { label: "立方体", value: "fas fa-cube" },
    { label: "立方体组", value: "fas fa-cubes" },
    { label: "实验瓶", value: "fas fa-flask" },
    { label: "实验瓶病毒", value: "fas fa-flask-vial" },
    { label: "齿轮", value: "fas fa-gear" },
    { label: "齿轮组", value: "fas fa-gears" },
    { label: "扳手", value: "fas fa-wrench" },
    { label: "代码", value: "fas fa-code" },
    { label: "代码分支", value: "fas fa-code-branch" },
    { label: "代码合并", value: "fas fa-code-merge" },
    { label: "代码提交", value: "fas fa-code-commit" },
    { label: "终端", value: "fas fa-terminal" },
    { label: "数据库", value: "fas fa-database" },
    { label: "云", value: "fas fa-cloud" },
    { label: "云上传", value: "fas fa-cloud-arrow-up" },
    { label: "云下载", value: "fas fa-cloud-arrow-down" },
    { label: "服务器", value: "fas fa-server" },
    { label: "网络", value: "fas fa-network-wired" },
    { label: "芯片", value: "fas fa-microchip" },
    { label: "内存", value: "fas fa-memory" },
    { label: "硬盘", value: "fas fa-hard-drive" },
    { label: "SD卡", value: "fas fa-sd-card" },
    { label: "USB", value: "fab fa-usb" },
    { label: "插头", value: "fas fa-plug" },
    { label: "电池", value: "fas fa-battery-full" },
    { label: "电池空", value: "fas fa-battery-empty" },

    // 设备图标
    { label: "笔记本电脑", value: "fas fa-laptop" },
    { label: "台式机", value: "fas fa-desktop" },
    { label: "手机", value: "fas fa-mobile" },
    { label: "平板", value: "fas fa-tablet" },
    { label: "打印机", value: "fas fa-print" },
    { label: "键盘", value: "fas fa-keyboard" },
    { label: "鼠标", value: "fas fa-computer-mouse" },
    { label: "摄像头", value: "fas fa-camera" },
    { label: "摄像头视频", value: "fas fa-video" },
    { label: "音响", value: "fas fa-volume-high" },
    { label: "耳机", value: "fas fa-headphones" },
    { label: "耳机简单", value: "fas fa-headphones-simple" },
    { label: "显示器", value: "fas fa-display" },
    { label: "电视", value: "fas fa-tv" },

    // 用户图标
    { label: "用户", value: "fas fa-user" },
    { label: "用户组", value: "fas fa-users" },
    { label: "用户加", value: "fas fa-user-plus" },
    { label: "用户减", value: "fas fa-user-minus" },
    { label: "用户叉", value: "fas fa-user-xmark" },
    { label: "用户医生", value: "fas fa-user-doctor" },
    { label: "用户秘密", value: "fas fa-user-secret" },
    { label: "用户朋友", value: "fas fa-user-group" },
    { label: "用户毕业帽", value: "fas fa-user-graduate" },
    { label: "用户齿轮", value: "fas fa-user-gear" },
    { label: "用户锁", value: "fas fa-user-lock" },
    { label: "机器人", value: "fas fa-robot" },
    { label: "头像", value: "fas fa-id-badge" },
    { label: "身份证", value: "fas fa-id-card" },

    // 图表图标
    { label: "图表柱状", value: "fas fa-chart-column" },
    { label: "图表折线", value: "fas fa-chart-line" },
    { label: "图表饼图", value: "fas fa-chart-pie" },
    { label: "图表面积", value: "fas fa-chart-area" },
    { label: "图表简单", value: "fas fa-chart-simple" },
    { label: "表格", value: "fas fa-table" },
    { label: "表格单元格", value: "fas fa-table-cells" },
    { label: "列表", value: "fas fa-list" },
    { label: "列表-ul", value: "fas fa-list-ul" },
    { label: "列表-ol", value: "fas fa-list-ol" },
    { label: "列表检查", value: "fas fa-list-check" },

    // 操作图标
    { label: "检查", value: "fas fa-square-check" },
    { label: "方框", value: "fas fa-square" },
    { label: "圆圈", value: "fas fa-circle" },
    { label: "圆点", value: "fas fa-circle-dot" },
    { label: "星标", value: "fas fa-star" },
    { label: "星标半", value: "fas fa-star-half" },
    { label: "心形", value: "fas fa-heart" },
    { label: "心形破碎", value: "fas fa-heart-crack" },
    { label: "铃铛", value: "fas fa-bell" },
    { label: "信封", value: "fas fa-envelope" },
    { label: "信封打开", value: "fas fa-envelope-open" },
    { label: "评论", value: "fas fa-comment" },
    { label: "评论组", value: "fas fa-comments" },
    { label: "评论医疗", value: "fas fa-comment-medical" },
    { label: "点赞", value: "fas fa-thumbs-up" },
    { label: "点踩", value: "fas fa-thumbs-down" },
    { label: "标记", value: "fas fa-bookmark" },
    { label: "标签", value: "fas fa-tag" },
    { label: "标签组", value: "fas fa-tags" },
    { label: "旗帜", value: "fas fa-flag" },
    { label: "旗帜检查", value: "fas fa-flag-checkered" },

    // 教育图标
    { label: "Graduation Cap", value: "fas fa-graduation-cap" },
    { label: "书本", value: "fas fa-book-open" },
    { label: "书本打开阅读", value: "fas fa-book-open-reader" },
    { label: "黑板", value: "fas fa-chalkboard" },
    { label: "黑板用户", value: "fas fa-chalkboard-user" },
    { label: "铅笔", value: "fas fa-pencil" },
    { label: "铅笔方", value: "fas fa-square-pen" },
    { label: "计算器", value: "fas fa-calculator" },
    { label: "原子", value: "fas fa-atom" },
    { label: "DNA", value: "fas fa-dna" },
    { label: "显微镜", value: "fas fa-microscope" },
    { label: "书签", value: "fas fa-bookmark" },

    // 商业图标
    { label: "购物车", value: "fas fa-cart-shopping" },
    { label: "购物袋", value: "fas fa-bag-shopping" },
    { label: "购物篮", value: "fas fa-basket-shopping" },
    { label: "美元", value: "fas fa-dollar-sign" },
    { label: "欧元", value: "fas fa-euro-sign" },
    { label: "英镑", value: "fas fa-pound-sign" },
    { label: "人民币", value: "fas fa-yen-sign" },
    { label: "信用卡", value: "fas fa-credit-card" },
    { label: "货币", value: "fas fa-money-bill" },
    { label: "货币波浪", value: "fas fa-money-bill-wave" },
    { label: "图表线", value: "fas fa-chart-line" },
    { label: "钱包", value: "fas fa-wallet" },
    { label: "保险箱", value: "fas fa-vault" },
    { label: "收据", value: "fas fa-receipt" },
    { label: "发票", value: "fas fa-file-invoice" },
    { label: "发票美元", value: "fas fa-file-invoice-dollar" },

    // 建筑图标
    { label: "建筑", value: "fas fa-building" },
    { label: "医院", value: "fas fa-hospital" },
    { label: "医院用户", value: "fas fa-hospital-user" },
    { label: "学校", value: "fas fa-school" },
    { label: "商店", value: "fas fa-store" },
    { label: "家", value: "fas fa-house" },
    { label: "家医疗", value: "fas fa-house-medical" },
    { label: "家用户", value: "fas fa-house-user" },
    { label: "地标", value: "fas fa-landmark" },
    { label: "地标圆顶", value: "fas fa-landmark-dome" },

    // 交通图标
    { label: "汽车", value: "fas fa-car" },
    { label: "汽车侧", value: "fas fa-car-side" },
    { label: "自行车", value: "fas fa-bicycle" },
    { label: "摩托车", value: "fas fa-motorcycle" },
    { label: "飞机", value: "fas fa-plane" },
    { label: "飞机起飞", value: "fas fa-plane-departure" },
    { label: "飞机到达", value: "fas fa-plane-arrival" },
    { label: "轮船", value: "fas fa-ship" },
    { label: "火车", value: "fas fa-train" },
    { label: "地铁", value: "fas fa-subway" },
    { label: "出租车", value: "fas fa-taxi" },
    { label: "公交车", value: "fas fa-bus" },
    { label: "货车", value: "fas fa-truck" },
    { label: "货车快速", value: "fas fa-truck-fast" },

    // 生活图标
    { label: "床", value: "fas fa-bed" },
    { label: "餐具", value: "fas fa-utensils" },
    { label: "咖啡", value: "fas fa-mug-saucer" },
    { label: "啤酒", value: "fas fa-beer-mug-empty" },
    { label: "叶子", value: "fas fa-leaf" },
    { label: "树", value: "fas fa-tree" },
    { label: "太阳", value: "fas fa-sun" },
    { label: "月亮", value: "fas fa-moon" },
    { label: "闪电", value: "fas fa-bolt" },
    { label: "火", value: "fas fa-fire" },
    { label: "水滴", value: "fas fa-droplet" },
    { label: "磁铁", value: "fas fa-magnet" },
    { label: "药丸", value: "fas fa-pills" },
    { label: "注射器", value: "fas fa-syringe" },
    { label: "重量", value: "fas fa-weight-scale" },

    // 符号图标
    { label: "星号", value: "fas fa-asterisk" },
    { label: "邮箱", value: "fas fa-at" },
    { label: "版权", value: "fas fa-copyright" },
    { label: "注册", value: "fas fa-registered" },
    { label: "商标", value: "fas fa-trademark" },
    { label: "搜索", value: "fas fa-magnifying-glass" },
    { label: "搜索减", value: "fas fa-magnifying-glass-minus" },
    { label: "搜索加", value: "fas fa-magnifying-glass-plus" },
    { label: "下载", value: "fas fa-download" },
    { label: "上传", value: "fas fa-upload" },
    { label: "分享", value: "fas fa-share" },
    { label: "分享节点", value: "fas fa-share-nodes" },
    { label: "外部链接", value: "fas fa-arrow-up-right-from-square" },
    { label: "链接", value: "fas fa-link" },
    { label: "链接斜杠", value: "fas fa-link-slash" },
    { label: "解锁", value: "fas fa-unlock" },
    { label: "锁定", value: "fas fa-lock" },
    { label: "钥匙", value: "fas fa-key" },
    { label: "签名", value: "fas fa-signature" },
    { label: "无限", value: "fas fa-infinity" },
    { label: "百分比", value: "fas fa-percent" },

    // 箭头图标
    { label: "箭头上", value: "fas fa-arrow-up" },
    { label: "箭头右", value: "fas fa-arrow-right" },
    { label: "箭头下", value: "fas fa-arrow-down" },
    { label: "箭头左", value: "fas fa-arrow-left" },
    { label: "箭头右转", value: "fas fa-arrow-rotate-right" },
    { label: "箭头左转", value: "fas fa-arrow-rotate-left" },
    { label: "箭头趋势上升", value: "fas fa-arrow-trend-up" },
    { label: "箭头趋势下降", value: "fas fa-arrow-trend-down" },
    { label: "角度上", value: "fas fa-angle-up" },
    { label: "角度右", value: "fas fa-angle-right" },
    { label: "角度下", value: "fas fa-angle-down" },
    { label: "角度左", value: "fas fa-angle-left" },
    { label: "播放", value: "fas fa-play" },
    { label: "暂停", value: "fas fa-pause" },
    { label: "停止", value: "fas fa-stop" },
    { label: "前进", value: "fas fa-forward" },
    { label: "后退", value: "fas fa-backward" },
    { label: "快进", value: "fas fa-forward-fast" },
    { label: "快退", value: "fas fa-backward-fast" },

    // 时间图标
    { label: "时钟", value: "fas fa-clock" },
    { label: "日历", value: "fas fa-calendar" },
    { label: "日历日", value: "fas fa-calendar-day" },
    { label: "日历周", value: "fas fa-calendar-week" },
    { label: "日历月", value: "fas fa-calendar-days" },
    { label: "定时器", value: "fas fa-hourglass" },
    { label: "定时器空", value: "fas fa-hourglass-empty" },
    { label: "定时器结束", value: "fas fa-hourglass-end" },

    // 新增图标
    { label: "灯泡", value: "fas fa-lightbulb" },
    { label: "公文包", value: "fas fa-briefcase" },
    { label: "地图", value: "fas fa-map" },
    { label: "地图标记", value: "fas fa-map-marker" },
    { label: "地图位置", value: "fas fa-location-dot" },
    { label: "地球", value: "fas fa-earth-americas" },
    { label: "地球欧洲", value: "fas fa-earth-europe" },
    { label: "地球亚洲", value: "fas fa-earth-asia" },
    { label: "wifi", value: "fas fa-wifi" },
    { label: "rss", value: "fas fa-rss" },
    { label: "rss平方", value: "fas fa-rss-square" },
    { label: "礼物", value: "fas fa-gift" },
    { label: "奖杯", value: "fas fa-trophy" },
    { label: "奖牌", value: "fas fa-medal" },
    { label: "盾牌", value: "fas fa-shield" },
    { label: "盾牌半", value: "fas fa-shield-halved" },
    { label: "盾牌病毒", value: "fas fa-shield-virus" },
    { label: "口罩", value: "fas fa-mask-face" },
    { label: "病毒", value: "fas fa-virus" },
    { label: "病毒斜杠", value: "fas fa-virus-slash" },
    { label: "病毒新冠", value: "fas fa-virus-covid" },
    { label: "温度空", value: "fas fa-temperature-empty" },
    { label: "温度四分之一", value: "fas fa-temperature-quarter" },
    { label: "温度半", value: "fas fa-temperature-half" },
    { label: "温度四分之三", value: "fas fa-temperature-three-quarters" },
    { label: "温度全", value: "fas fa-temperature-full" },

    // 视频图标
    { label: "播放", value: "fas fa-play" },
    { label: "暂停", value: "fas fa-pause" },
    { label: "停止", value: "fas fa-stop" },
    { label: "前进", value: "fas fa-forward" },
    { label: "后退", value: "fas fa-backward" },
    { label: "快进", value: "fas fa-forward-fast" },
    { label: "快退", value: "fas fa-backward-fast" },
    { label: "播放圆形", value: "fas fa-circle-play" },
    { label: "暂停圆形", value: "fas fa-circle-pause" },
    { label: "停止圆形", value: "fas fa-circle-stop" },
    { label: "视频", value: "fas fa-video" },
    { label: "录制", value: "fas fa-record-vinyl" },
    { label: "剪辑", value: "fas fa-clapperboard" },
    { label: "电影", value: "fas fa-film" },
    { label: "电视", value: "fas fa-tv" },
    { label: "摄像头", value: "fas fa-camera" },
    { label: "摄像头旋转", value: "fas fa-camera-rotate" },
];
